server:
  port: 8089

spring:
  mvc:
    favicon:
      enable: false
  datasource:
    url: jdbc:mysql://localhost:3306/garbage?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Wenpd$1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true