server:
  port: 5000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: login_route
        uri: lb://garbage-service
        predicates:
          - Path=/auth/**
        filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
      - id: token_route
        uri: lb://garbage-service
        predicates:
          - Query=loginToken
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/garbage/failure

logging:
  level:
    org.springframework.cloud.gateway: debug